// Copyright (c) 2020, ellie/@ell1e & Horse64 Team (see AUTHORS.md),
// also see LICENSE.md file.
// SPDX-License-Identifier: BSD-2-Clause

#ifndef HORSE64_COMPILER_GLOBALLIMITS_H_
#define HORSE64_COMPILER_GLOBALLIMITS_H_


#define H64LIMIT_SOURCEFILESIZE (10 * 1024 * 1024)
#define H64LIMIT_IDENTIFIERLEN (256)
#define H64LIMIT_MAXPARSERECURSION 64
#define H64LIMIT_IMPORTCHAINLEN 32

#endif  // HORSE64_COMPILER_GLOBALLIMITS_H_
