name: Basic build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Cache docker image
      uses: actions/cache@v2
      env:
        cache-name: cache-core-horse64-buildimage
      with:
        path: ~/.local/share/core.horse64.org-dockerimage/
        key: cache-core-horse64-buildimage-v2
        restore-keys: |
          cache-core-horse64-buildimage-v2

    - name: run docker
      run: python3 tools/compile-docker.py --run-tests --cache-image
