name: Basic build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - name: run docker
      run: python3 tools/compile-docker.py --run-tests
